// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opxjgdrbnizmnyegktze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9weGpnZHJibml6bW55ZWdrdHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjYyODMsImV4cCI6MjA3MTgwMjI4M30.TRjd3HpVbBX4Cq0fz2C9qS4PZKUC8lxABtX2-98LcDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});